name: UPDATE-ALL

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  UPDATE-ALL:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update all
        run:  |
          echo "Update the mailles files"
          ./SCRIPTS/UPDATE-MAILLES.ps1
          echo "Create the database"
          ./SCRIPTS/CREATE-TOTAL.ps1
          echo "Search for sightings after 2019"
          ./SCRIPTS/SEARCH-2019.ps1
          echo "Search for never seen species"
          ./SCRIPTS/SEARCH-BLANKS.ps1
          
      - name: Retry if failed
        if: failure()
        run:  |
          echo "Update the mailles files"
          ./SCRIPTS/UPDATE-MAILLES.ps1
          echo "Create the database"
          ./SCRIPTS/CREATE-TOTAL.ps1
          echo "Search for sightings after 2019"
          ./SCRIPTS/SEARCH-2019.ps1
          echo "Search for never seen species"
          ./SCRIPTS/SEARCH-BLANKS.ps1
